name: Build
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allow manual triggering
  pull_request:

env:
  ADMIN_IMAGE: authexec/reactive-tools:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: reactive_crypto check
      run: cargo check --manifest-path reactive_crypto/Cargo.toml
    -
      name: reactive_net check
      run: cargo check --manifest-path reactive_net/Cargo.toml
    -
      name: sgx_attestation check
      run: |
        docker pull ${{ env.ADMIN_IMAGE }}
        shopt -s expand_aliases
        alias CHECK="docker run --rm -v $(pwd)/sgx_attestation:/usr/src/app/ ${{ env.ADMIN_IMAGE }} cargo check"
        CHECK --features=client,client_verbose
        CHECK --features=sp,sp_verbose
        CHECK --target=x86_64-fortanix-unknown-sgx --features=enclave,enclave_verbose
        unalias CHECK
